name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: "build-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: true

env:
  STORAGE_NONSENSE_VERSION: 1.1.1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: Setup dotnet
          uses: actions/setup-dotnet@v6
          with:
              dotnet-version: '10.0.x'

        - name: Checkout
          uses: actions/checkout@v7

        - name: Build
          run: dotnet build -c Release

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.head_commit.message, '[Deploy]') && github.event_name == 'push'
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
    steps:
        - name: Setup dotnet
          uses: actions/setup-dotnet@v6
          with:
              dotnet-version: '10.0.x'

        - name: Checkout
          uses: actions/checkout@v7

        - name: Publish
          run: dotnet publish -o publish /nowarn:NETSDK1194

        - name: Attest
          uses: actions/attest@v4
          with:
            subject-path: 'publish/StorageNonsense.exe'

        - name: Create GitHub Release
          uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: v${{ env.STORAGE_NONSENSE_VERSION }}
            name: Storage Nonsense v${{ env.STORAGE_NONSENSE_VERSION }}
            files: |
              ./publish/StorageNonsense.exe
            body_path: RELEASE_NOTES.md
            target_commitish: ${{ github.event.head_commit.id }}
            make_latest: true
